### ISSUE TITLE
The need for jquery.metadata plugin is not necessary with current jquery 

### ISSUE THREAD

**Issue by CoreyWinkelmannPP** [bramstein/jlayout#1]
The jquery.jlayout.js file could be updated to use html5 data- attributes which is built into jquery 1.4.3 +. That way the metadata plugin can be removed. Below I highlight the change that I believe needs to be made. I have included a version that still checks for the metadata plugin just in case you want to keep the check around for people that are still using it.
# jquery.jlayout.js
## current:

```javascript line 121
o = $.metadata && element.metadata().layout ? $.extend(opts, element.metadata().layout) : opts,

``````

## html5 data- attribute only:  
```javascript line 121
o = element.data('layout') ? $.extend(opts, element.data('layout')) : opts,
``````
## backwards compatibility:

```javascript line 121
o = element.data('layout') ? $.extend(opts, element.data('layout')) : ( $.metadata && element.metadata().layout ) ? $.extend(opts, element.metadata().layout) : opts,

```

# Little tip as far as jquery and data- attributes are concerned:
The attribute has single quotes around js objects instead of double quotes

    <div data-layout='{"type": "grid", "hgap": 3, "vgap": 3}' class="column"></div>
```

**Comment by bramstein** [comment]
Hi,

Looks good! I'd be happy to make the changes, could you do a pull
request? I'll need to add a README with a contributors section now :)

On Thu, Jun 2, 2011 at 9:30 PM, cawinkelmann
reply@reply.github.com
wrote:
