### ISSUE TITLE
jQuery UI 1.10.1 - Accordion.resize no longer works in demo

### ISSUE THREAD

**Issue by JeBuSBrian** [bramstein/jlayout#5]
Upgrade to jQuery 1.9.1 and jQuery UI 1.10.1 caused the accordion to stop functioning.  The line: 
$('#accordion').accordion('resize');
Causes the following js error:
Error: cannot call methods on accordion prior to initialization; attempted to call method 'resize'

If you comment out that line, the accordion works, but it no longer fills the east div.

Changing this line:
$('#accordion').accordion({header: 'h3', fillSpace: true})
to:
$('#accordion').accordion({header: 'h3', heightStyle: "fill"});
Results in the accordion filling the east div, but only for the initial window size.  Any resize, and the accordion doesn't update.

Any suggestions on how to fix this?

**Comment by JeBuSBrian** [comment]
And of course, not more than 2 minutes after posting, I discovered the solution.  Or a possible solution, anyway.

The accordion must be initialized prior to the layout function, rather than after:
$('#accordion').accordion({header: 'h3', heightStyle: "fill"});

Then inside the layout function, change the resize line to refresh:
$('#accordion').accordion('refresh');

This will make it work with jQuery 1.9.1 and jQuery UI 1.10.1

**Comment by bramstein** [comment]
Ah, the accordion seems to have some API changes. Thanks for finding that out!
